version: "3.9"
services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:

      MYSQL_ROOT_PASSWORD: pass_root
      MYSQL_DATABASE: blackjack
      MYSQL_USER: user
      MYSQL_PASSWORD: user_pass
    ports:
      - "3310:3306"

  mongo:
    image: mongo:6
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
