version: "3.8"
services:
  mysql:
    image: mysql:8.4
    container_name: bj-mysql
    ports:
      - "3310:3306"
    environment:
      MYSQL_DATABASE: blackjack
      MYSQL_USER: user
      MYSQL_PASSWORD: user_pass
      MYSQL_ROOT_PASSWORD: root
    command: >
      --default-authentication-plugin=caching_sha2_password
      --lower_case_table_names=1
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 20

  mongo:
    image: mongo:7
    container_name: bj-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 5s
      timeout: 3s
      retries: 20
